export const subjectName = [
  "Math1 คณิตศาสตร์ประยุกต์ 1",
  "Math2 คณิตศาสตร์ประยุกต์ 2",
  "Science วิทยาศาสตร์ประยุกต์",
  "Physic ฟิลิกส์",
  "Chemistry เคมี",
  "Biology ชีววิทยา",
  "Social สัมคมศึกษา",
  "Thai ภาษาไทย",
  "English ภาษาอังกฤษ",
  "French ภาษาฝรั่งเศส",
  "German ภาษาเยอรมัน",
  "Japanese ภาษาญี่ปุ่น",
  "Korean ภาษาเกาหลี",
  "Chinese ภาษาจีน",
  "Pali ภาษาบาลี",
  "Spain ภาษาสเปน",
]